// import { Metadata } from "next";
// import Image from "next/image";
// import "./globals.css";

import { Separator } from "@/components/ui/separator";
import { SidebarNav } from "./components/sidebar-nav";

// export const metadata: Metadata = {
//   title: "Admin Dashboard",
//   description: "Admin Dashboard | Operations CRUD pour conducteurs, passagers, trajets, et plus.",
// };

const sidebarNavItems = [
  {
    title: "Profile Admin",
    href: "/",
  },
  {
    title: "Conducteurs",
    href: "/conducteurs",
  },
  {
    title: "Passagers",
    href: "/passagers",
  },
  {
    title: "Trajets",
    href: "/trajets",
  },
];

// interface SettingsLayoutProps {
//   children: React.ReactNode;
// }

// export default function SettingsLayout({ children }: SettingsLayoutProps) {
//   return (
//     <>
//       {/* <div className='md:hidden'>
//         <Image
//           src='/examples/forms-light.png'
//           width={1280}
//           height={791}
//           alt='Forms'
//           className='block dark:hidden'
//         />
//         <Image
//           src='/examples/forms-dark.png'
//           width={1280}
//           height={791}
//           alt='Forms'
//           className='hidden dark:block'
//         />
//       </div> */}
// <div className='hidden space-y-6 p-10 pb-16 md:block'>
//   <div className='space-y-0.5'>
//     <h2 className='text-2xl font-bold tracking-tight'>Admin Dashboard</h2>
//     <p className='text-muted-foreground'>
//       Interface centralisée permettant aux administrateurs de gérer les
//       trajets, les conducteurs, les passagers, les paiements et autres
//       aspects liés à la plateforme de covoiturage.
//     </p>
//   </div>
//   <Separator className='my-6' />
//   <div className='flex flex-col space-y-8 lg:flex-row lg:space-x-12 lg:space-y-0'>
//     <aside className='-mx-4 lg:w-1/5'>
//       <SidebarNav items={sidebarNavItems} />
//     </aside>
//     <div className='flex-1'>{children}</div>
//   </div>
// </div>
//     </>
//   );
// }
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserNav } from "./(conducteurs)/components/user-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='hidden space-y-6 pt-10 px-20 pb-16 md:block'>
          <div className='space-y-0.5 flex justify-between'>
            <div>
              <h2 className='text-2xl font-bold tracking-tight'>Admin Dashboard</h2>
              <p className='text-muted-foreground'>
                Interface centralisée permettant aux administrateurs de gérer les trajets, les conducteurs, les
                passagers, les paiements et autres aspects liés à la plateforme de covoiturage.
              </p>
            </div>
            <div className='flex items-center space-x-2'>
              <UserNav />
            </div>
          </div>
          <Separator className='my-6' />
          <div className='flex flex-col space-y-8 lg:flex-row lg:space-x-12 lg:space-y-0'>
            <aside className='-mx-4 lg:w-1/5'>
              <SidebarNav items={sidebarNavItems} />
            </aside>
            <div className='flex-1'>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
